name: API Test Suite CI / CD Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - "qa"
        default: "qa"
      suite:
        description: "Suite"
        required: true
        type: choice
        options:
          - "regression"
          - "sanity"
        default: "regression"
      instances:
        description: "Parallel instances"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
          - "4"
        default: "1"

jobs:
  test-execution:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      SUITE: ${{ github.event.inputs.suite }}
      INSTANCES: ${{ github.event.inputs.instances }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: |
          docker build -t python-api-testing-container .
      
      - name: Run the Docker Container
        run: |
          docker run \
          -e SUITE=${{ env.SUITE }} \
          -e INSTANCES=${{ env.INSTANCES }} \
          -v ${PWD}/allure-results:/opt/pysetup/allure-results \
          python-api-testing-container

      - name: Generate Allure Report and Send Notifications
        run: |
          cd allure-results
          ls -a
          python src/utils/test_summary_extractor.py
          bash scripts/util-scripts/discord-notification.sh
          bash scripts/util-scripts/slack-notification.sh

      - name: Upload Allure Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

      - name: Upload Allure Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1